<?php

/**
 * Implements hook menu
 */
function locguide_menu() {
	$items['admin/config/locguide'] = array(
		'title' => 'Location Guides',
		'description' => 'Adjust Location Guide Settings for Library Resources',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	$items['admin/config/locguide/areamap'] = array(
		'page callback' => 'locguide_admin_areamaps',
		'file' => 'locguide.admin.inc',
		'title' => 'Area Maps',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['admin/config/locguide/areamap/new'] = array(
		'type' => MENU_LOCAL_TASK,
		'title' => 'New Area Map',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_areamap_form'),
		'file' => 'locguide.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/areamap/%locguide_areamap/edit'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_areamap_form', 4),
		'file' => 'locguide.admin.inc',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_TASK,
	);
	$items['admin/config/locguide/locmap'] = array(
		'type' => MENU_NORMAL_ITEM,
		'title' => 'Location Maps',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_locmaps'),
		'file' => 'locguide.locmap.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/collgroup'] = array(
		'page callback' => 'locguide_admin_collgroups',
		'title' => 'Collection Groups',
		'file' => 'locguide.collgroup.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/collgroup/new'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_collgroup_form', 'new', locguide_admin_model_data('collgroup_form')),
		'title' => 'Create Collection Group',
		'file' => 'locguide.collgroup.admin.inc',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_ACTION,
	);
	$items['admin/config/locguide/collgroup/%locguide_collgroup/edit'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_collgroup_form', 4, locguide_admin_model_data('collgroup_form')),
		'title' => 'Edit Collection Group',
		'file' => 'locguide.collgroup.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/sublibrary'] = array(
		'page callback' => 'locguide_admin_sublibraries',
		'title' => 'Sublibraries',
		'file' => 'locguide.sublibrary.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/sublibrary/new'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_sublibrary_form', 'new', locguide_admin_model_data('sublibrary_form')),
		'title' => 'Create Sublibrary',
		'file' => 'locguide.sublibrary.admin.inc',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_ACTION,
	);
	$items['admin/config/locguide/sublibrary/%locguide_sublibrary/edit'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_sublibrary_form', 4, locguide_admin_model_data('sublibrary_form')),
		'title' => 'Edit Sublibrary',
		'file' => 'locguide.sublibrary.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/externallink'] = array(
		'page callback' => 'locguide_admin_externallinks',
		'title' => 'External Links',
		'file' => 'locguide.externallink.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/externallink/new'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_externallink_form', 'new', locguide_admin_model_data('externallink_form')),
		'title' => 'Create External Link',
		'file' => 'locguide.externallink.admin.inc',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_ACTION,
	);
	$items['admin/config/locguide/externallink/%locguide_externallink/edit'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_externallink_form', 4, locguide_admin_model_data('externallink_form')),
		'title' => 'Edit External Link',
		'file' => 'locguide.externallink.admin.inc',
		'access arguments' => array('administer site configuration'),
	);

	$items['admin/config/locguide/genericmessage'] = array(
		'page callback' => 'locguide_admin_genericmessages',
		'title' => 'Generic Messages',
		'file' => 'locguide.genericmessage.admin.inc',
		'access arguments' => array('administer site configuration'),
	);
	$items['admin/config/locguide/genericmessage/new'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_genericmessage_form', 'new', locguide_admin_model_data('genericmessage_form')),
		'title' => 'Create Generic Message',
		'file' => 'locguide.genericmessage.admin.inc',
		'access arguments' => array('administer site configuration'),
		'type' => MENU_LOCAL_ACTION,
	);
	$items['admin/config/locguide/genericmessage/%locguide_genericmessage/edit'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('locguide_admin_genericmessage_form', 4, locguide_admin_model_data('genericmessage_form')),
		'title' => 'Edit Generic Message',
		'file' => 'locguide.genericmessage.admin.inc',
		'access arguments' => array('administer site configuration'),
	);

	$items['areamap/%locguide_areamap'] = array(
		'type' => MENU_CALLBACK,
		'page callback' => 'locguide_areamap',
		'page arguments' => array(1),
		'file' => 'locguide.pages.areamap.inc',
		'access callback' => TRUE,
	);
	$items['find/barcode'] = array(
		'page callback' => 'locguide_find_barcode',
		'title' => 'Find Barcode',
		'type' => MENU_CALLBACK,
		'access callback' => TRUE,
	);
	$items['find/label'] = array(
		'page callback' => 'locguide_find_label',
		'title' => 'Find by Label',
		'type' => MENU_CALLBACK,
		'access callback' => TRUE,
	);

	return $items;
}

/**
 * Implements hook_permission()
 */
function locguide_permission() {
	return array(
		'administer location guides' => array(
			'title' => t('Administer Location Guides'),
			'description' => t('Perform administrative tasks for locations guides data'),
		),
	);
}

/**
 * Implements hook_init()
 * load content_type/model mapping into session
 */
function locguide_init() {
	if (path_is_admin(current_path()) && (strpos(current_path(), 'locguide') !== FALSE)) {
		// load contents of django_content_type
		_locguide_load_content_types();
	}
}

function _locguide_load_content_types() {
	$content_type_data = &drupal_static(__FUNCTION__);
	if (!isset($content_type_data)) {
		if ($cache = cache_get('locguide_content_types')) {
			$content_type_data = $cache->data;
		} else {
			$content_type_data = array();
			db_set_active('locationguide');
			
			$result = db_select('django_content_type', 'ct')
				->fields('ct')
				->execute();
			foreach ($result as $ctype) {
				$key = sprintf("%s:%s", $ctype->app_label, $ctype->model);
				$content_type_data[$key] = $ctype;
			}
			db_set_active();
			cache_set('locguide_content_types', $content_type_data, 'cache');
		}
	}
	return $content_type_data;
}

/**
 * Implements hook_theme()
 */
function locguide_theme($existing, $type, $theme, $path) {
	$items['areamap'] = array(
		'function' => 'locguide_theme_areamap',
		'file' => 'locguide.pages.areamap.inc',
		'variables' => array('areamap' => NULL),
	);
	$items['area-map'] = array(
		'template' => 'area-map',
		'variables' => array('locMap' => NULL),
		'path' => $path . '/theme',
	);
	$items['external-link'] = array(
		'template' => 'external-link',
		'variables' => array('extLink' => NULL),
		'path' => $path . '/theme',
	);
	return $items;
}

/**
 * Model data for various admin forms
 */
function locguide_admin_model_data($context) {
	$model = array();
	if ($context == 'collgroup_form') {
		$sublibraries = SubLibrary::sublibraries(1);
		foreach ($sublibraries as $sl) {
			$model['options']['sublibrary'][$sl->id] = $sl->label;
		}
	}
	if ($context == 'sublibrary_form') {
		$locationmaps = LocMapManager::locationMaps();
		foreach ($locationmaps as $l) {
			$model['options']['locationmap'][$l->id] = sprintf("%s %s", $l->sublibrary_label, $l->collgroup_description);
		}
	}
	if ($context == 'locmap_form') {
		
	}
	if ($context == 'externallink_form') {
		$genericmessges = GenericMessage::genericMessages();
		foreach ($genericmessges as $m) {
			$model['options']['genericmessage'][$m->id] = $m->label;
		}
	}
	return $model;
}
/**
 * Auto-loader for Area Map
 */
function locguide_areamap_load($areamap_id) {
	db_set_active('locationguide');
	$query = db_select('locationguide_areamap', 'am')
		->fields('am')
		->condition('am.id', $areamap_id);

	$result = $query->execute();

	$o = $result->fetchObject();

	db_set_active();
	return $o;
}

/**
 * Auto-loader for Collection Group
 */
function locguide_collgroup_load($id) {
	db_set_active('locationguide');
	$query = db_select('locationguide_collectiongroup', 'cg')
		->fields('cg')
		->condition('cg.id', $id);
	$result = $query->execute();
	$o = $result->fetchObject();
	db_set_active();
	return $o;
}

/**
 * Auto-loader for Sublibrary
 */
function locguide_sublibrary_load($id) {
	db_set_active('locationguide');
	$query = db_select('locationguide_sublibrary', 'sl')
		->fields('sl')
		->condition('sl.id', $id);
	$result = $query->execute();
	$o = $result->fetchObject();
	db_set_active();
	return $o;	
}

/**
 * Auto-loader for Generic Message
 */
function locguide_genericmessage_load($id) {
	db_set_active('locationguide');
	$query = db_select('locationguide_genericmessage', 'm')
		->fields('m')
		->condition('m.id', $id);
	$result = $query->execute();
	$o = $result->fetchObject();
	$o->external_links = array();
	
	$result = db_select('locationguide_externallink', 'e')
		->fields('e')
		->condition('e.generic_msg_id', $id)
		->orderBy('e.title')
		->execute();
	foreach ($result as $extlink) {
		$o->external_links[] = $extlink;
	}
	db_set_active();
	return $o;	
}

/**
 * Auto-loader for Generic Message
 */
function locguide_externallink_load($id) {
	db_set_active('locationguide');
	$query = db_select('locationguide_externallink', 'm')
		->fields('m')
		->condition('m.id', $id);
	$result = $query->execute();
	$o = $result->fetchObject();
	$o->external_links = array();
	db_set_active();
	return $o;	
}

function locguide_find_label($label) {
	return 'Happy';
}

function locguide_find_barcode($barcode) {
	# emulate the Django project's barcode retrieval
	# http://dev.library.duke.edu/apps/locationguide/find/HBBQ-7285-00001__

	# create a model for Location Map
	$model = new LocMapManager();
	$locMap = $model->getLocationMapByBarcode($barcode);
	if (!is_null($locMap->areaMap)) {
		dpm($locMap->areaMap);
		return theme('area-map', array('areaMap' => $locMap->areaMap));
	} elseif (!is_null($locMap->externalLink)) {
		dpm($locMap->externalLink);		
		drupal_set_title($locMap->externalLink->extlink_title);
		return theme('external-link', array('extLink' => $locMap->externalLink));
	}

	return 'Happy';
}
