<?php

/**
 * Implements hook_menu
 */
function libcatalog_menu() {
	$items['xtest'] = array(
		'page callback' => 'libcatalog_xtest',
		'access callback' => TRUE,
		'title' => 'XServer Test',
		'type' => MENU_CALLBACK,
	);
	$items['xtitletest'] = array(
		'page callback' => 'libcatalog_xtitle_test',
		'access callback' => TRUE,
		'title' => 'XServer Title Test',
		'type' => MENU_CALLBACK,
	);
	return $items;
}

/**
 * Implements hook_theme
 */
function libcatalog_theme() {
	return array(
		'area-map' => array(
			'template' => 'area-map',
			'variables' => array('locMap' => NULL),
		),
		'external-link' => array(
			'template' => 'external-link',
			'variables' => array('extLink' => NULL),
		),
	);
}

function libcatalog_xtest($barcode = NULL) {
	global $conf;
	dpm($barcode);
	# http://dev.library.duke.edu/apps/locationguide/find/HBBQ-7285-00001__

	# create a model for Location Map
	
	$model = new LocMapManager();
	
	try {
		$locMap = $model->getLocationMapByBarcode($barcode);
		if (!is_null($locMap->areaMap)) {
			dpm($locMap->areaMap);
		} elseif(!is_null($locMap->externalLink)) {
			dpm($locMap->externalLink);
		}
	} catch(Exception $x) {
		
	}

	return 'Happy';
}

function libcatalog_xtitle_test($sysno) {
	#http://search.library.duke.edu/search?id=DUKE002924985
	$bibTitle = BibTitle::newBibTitleFromSysNo($sysno);
	return 'Hello';
}
